Category.create!([
                     {name: "Pierogi"},
                     {name: "Bunny Chow"},
                     {name: "Pasta Carbonara"}
                 ])
Product.create!([
                    {name: "Meatballs with Sauce", price: "116.0", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.", img_url: File.open(Rails.root + "db/images_seed/deniz-altindas-38863-unsplash.jpg"), category_id: 3},
                    {name: "Tiramisù", price: "173.0", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant.", img_url: File.open(Rails.root + "db/images_seed/nordwood-themes-182310-unsplash.jpg"), category_id: 2},
                    {name: "Caesar Salad", price: "115.0", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.", img_url: File.open(Rails.root + "db/images_seed/alison-marras-323017-unsplash.jpg"), category_id: 2},
                    {name: "Philadelphia Maki", price: "171.0", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.", img_url: File.open(Rails.root + "db/images_seed/bobby-rodriguezz-1043119-unsplash.jpg"), category_id: 3},
                    {name: "Cauliflower Penne", price: "22.0", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham.", img_url: File.open(Rails.root + "db/images_seed/brooke-lark-186926-unsplash.jpg"), category_id: 1},
                    {name: "Chicken Fajitas", price: "140.0", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham.", img_url: File.open(Rails.root + "db/images_seed/brooke-lark-200710-unsplash.jpg"), category_id: 1},
                    {name: "Massaman Curry", price: "190.0", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant.", img_url: File.open(Rails.root + "db/images_seed/brooke-lark-230642-unsplash.jpg"), category_id: 2},
                    {name: "Bunny Chow", price: "89.0", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham.", img_url: File.open(Rails.root + "db/images_seed/brooke-lark-261287-unsplash.jpg"), category_id: 1},
                    {name: "Sushi", price: "99.0", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream.", img_url: File.open(Rails.root + "db/images_seed/dragne-marius-117368-unsplash.jpg"), category_id: 3},
                    {name: "Poutine", price: "189.0", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder.", img_url: File.open(Rails.root + "db/images_seed/eaters-collective-172258-unsplash.jpg"), category_id: 3},
                    {name: "California Maki", price: "183.0", description: "Breaded fried chicken with waffles, and a side of maple syrup.", img_url: File.open(Rails.root + "db/images_seed/edgar-castrejon-459822-unsplash.jpg"), category_id: 2},
                    {name: "Hummus", price: "190.0", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream.", img_url: File.open(Rails.root + "db/images_seed/eiliv-sonas-aceron-1113078-unsplash.jpg"), category_id: 3},
                    {name: "Seafood Paella", price: "15.0", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits.", img_url: File.open(Rails.root + "db/images_seed/hanny-naibaho-313771-unsplash.jpg"), category_id: 2},
                    {name: "French Toast", price: "188.0", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant.", img_url: File.open(Rails.root + "db/images_seed/hessam-hojati-1260993-unsplash.jpg"), category_id: 1},
                    {name: "Pierogi", price: "87.0", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham.", img_url: File.open(Rails.root + "db/images_seed/ian-dooley-281897-unsplash.jpg"), category_id: 1},
                    {name: "Pork Belly Buns", price: "25.0", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast.", img_url: File.open(Rails.root + "db/images_seed/joseph-gonzalez-176749-unsplash.jpg"), category_id: 2},
                    {name: "Seafood Paella", price: "64.0", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast.", img_url: File.open(Rails.root + "db/images_seed/joseph-gonzalez-192345-unsplash.jpg"), category_id: 1},
                    {name: "Pasta Carbonara", price: "121.0", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides.", img_url: File.open(Rails.root + "db/images_seed/joseph-gonzalez-228027-unsplash.jpg"), category_id: 3},
                    {name: "Chicken Parm", price: "18.0", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast.", img_url: File.open(Rails.root + "db/images_seed/karly-gomez-216609-unsplash.jpg"), category_id: 1},
                    {name: "Cheeseburger", price: "74.0", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream.", img_url: File.open(Rails.root + "db/images_seed/karly-gomez-465274-unsplash.jpg"), category_id: 2},
                    {name: "Pizza", price: "129.0", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.", img_url: File.open(Rails.root + "db/images_seed/maria-mekht-159066-unsplash.jpg"), category_id: 2},
                    {name: "California Maki", price: "61.0", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.", img_url: File.open(Rails.root + "db/images_seed/olenka-kotyk-15382-unsplash.jpg"), category_id: 3},
                    {name: "Barbecue Ribs", price: "179.0", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant.", img_url: File.open(Rails.root + "db/images_seed/alison-marras-323017-unsplash.jpg"), category_id: 2},
                    {name: "Lasagne", price: "28.0", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant.", img_url: File.open(Rails.root + "db/images_seed/alex-loup-392625-unsplash.jpg"), category_id: 3},
                    {name: "Chicken Milanese", price: "18.0", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.", img_url: File.open(Rails.root + "db/images_seed/mariana-medvedeva-379662-unsplash.jpg"), category_id: 1},
                    {name: "Chilli con Carne", price: "162.0", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant.", img_url: File.open(Rails.root + "db/images_seed/margot-pandone-5628-unsplash.jpg"), category_id: 1},
                    {name: "French Fries with Sausages", price: "103.0", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham.", img_url: File.open(Rails.root + "db/images_seed/ornella-binni-151618-unsplash.jpg"), category_id: 1},
                    {name: "Lasagne", price: "47.0", description: "Breaded fried chicken with waffles, and a side of maple syrup.", img_url: File.open(Rails.root + "db/images_seed/nordwood-themes-182310-unsplash.jpg"), category_id: 1}
                ])
User.create!([
                 {name: 'Eduardo', email: 'evr.online.lessons@gmail.com', phone: '34 9 9113-9183', password: '123456'},
                 {name: 'Nelio', email: 'nelio.cursos@gmail.com', phone: '34 9 9000-0009', password: '123456'}
             ])
Role.create!([
                 {user_id: 1, ability: 'admin'},
                 {user_id: 2, ability: 'admin'}
             ])